import * as THREE from 'three';

/**
 * THREE.js Object3D를 OBJ Blob으로 변환 (MTL 메테리얼 포함)
 * @param object3D - Export할 3D 객체
 * @param filename - 파일명 (확장자 제외)
 * @param additionalRotation - 추가 회전값 (라디안, X축)
 * @returns OBJ 파일 Blob과 MTL 파일 Blob
 */
export function exportToOBJBlob(object3D: THREE.Object3D, filename: string = 'model', additionalRotation: number = 0): { objBlob: Blob; mtlBlob: Blob } {
  try {
    // 모든 메시 수집 및 변환
    const meshes: Array<{ geometry: THREE.BufferGeometry; material: THREE.Material | THREE.Material[] }> = [];

    object3D.traverse((child) => {
      if (child instanceof THREE.Mesh && child.geometry) {
        const geo = child.geometry.clone();

        // World matrix 적용 (현재 위치/회전/스케일 모두 포함)
        child.updateMatrixWorld(true);
        geo.applyMatrix4(child.matrixWorld);

        // 추가 회전 적용 (QR 판만 눕히기)
        if (additionalRotation !== 0) {
          const rotationMatrix = new THREE.Matrix4().makeRotationX(additionalRotation);
          geo.applyMatrix4(rotationMatrix);
        }

        meshes.push({ geometry: geo, material: child.material });
      }
    });

    if (meshes.length === 0) {
      throw new Error('No meshes found in object');
    }

    // 바운딩 박스 계산하여 바닥면 정렬
    const tempGroup = new THREE.Group();
    meshes.forEach(({ geometry }) => {
      const mesh = new THREE.Mesh(geometry);
      tempGroup.add(mesh);
    });
    const box = new THREE.Box3().setFromObject(tempGroup);
    const offsetY = -box.min.y;

    // OBJ 문자열 생성
    let objString = `# Generated by 3D QR Platform\n`;
    objString += `mtllib ${filename}.mtl\n\n`;

    let vertexOffset = 1;

    meshes.forEach(({ geometry, material }) => {
      // 메테리얼 색상 감지
      let materialName = 'white';
      if (Array.isArray(material)) {
        material = material[0];
      }
      if (material instanceof THREE.MeshStandardMaterial || material instanceof THREE.MeshBasicMaterial) {
        const color = material.color;
        if (color.r < 0.1 && color.g < 0.1 && color.b < 0.1) {
          materialName = 'black';
        }
      }

      // 메테리얼 그룹 시작
      objString += `usemtl ${materialName}\n`;

      // Vertex 출력
      const positionAttr = geometry.attributes.position;
      if (!positionAttr) return;

      for (let i = 0; i < positionAttr.count; i++) {
        const x = positionAttr.getX(i);
        const y = positionAttr.getY(i) + offsetY;
        const z = positionAttr.getZ(i);
        objString += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
      }

      // Face 출력
      const index = geometry.index;
      if (index) {
        // Indexed geometry
        for (let i = 0; i < index.count; i += 3) {
          const a = index.getX(i) + vertexOffset;
          const b = index.getX(i + 1) + vertexOffset;
          const c = index.getX(i + 2) + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      } else {
        // Non-indexed geometry
        for (let i = 0; i < positionAttr.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += positionAttr.count;
      objString += '\n';
    });

    // MTL 파일 생성
    const mtlString = generateMTL(filename);

    // Blob 생성
    const objBlob = new Blob([objString], { type: 'text/plain' });
    const mtlBlob = new Blob([mtlString], { type: 'text/plain' });

    return { objBlob, mtlBlob };
  } catch (error) {
    console.error('OBJ export failed:', error);
    throw error;
  }
}

/**
 * MTL 파일 생성 (메테리얼 정보)
 * @param filename - 파일명
 * @returns MTL 문자열
 */
function generateMTL(filename: string): string {
  return `# Material file for ${filename}.obj
# Generated by 3D QR Platform

newmtl white
Ka 1.000 1.000 1.000
Kd 1.000 1.000 1.000
Ks 0.500 0.500 0.500
Ns 96.078431
d 1.000000
illum 2

newmtl black
Ka 0.000 0.000 0.000
Kd 0.000 0.000 0.000
Ks 0.500 0.500 0.500
Ns 96.078431
d 1.000000
illum 2
`;
}

/**
 * THREE.js Object3D를 OBJ 파일로 변환하여 다운로드
 * @param object3D - Export할 3D 객체
 * @param filename - 저장할 파일명 (확장자 제외)
 */
export function exportToOBJ(object3D: THREE.Object3D, filename: string = 'model') {
  try {
    const { objBlob, mtlBlob } = exportToOBJBlob(object3D, filename);

    // OBJ 파일 다운로드
    const objLink = document.createElement('a');
    objLink.href = URL.createObjectURL(objBlob);
    objLink.download = `${filename}.obj`;
    objLink.click();
    URL.revokeObjectURL(objLink.href);

    // MTL 파일 다운로드
    const mtlLink = document.createElement('a');
    mtlLink.href = URL.createObjectURL(mtlBlob);
    mtlLink.download = `${filename}.mtl`;
    mtlLink.click();
    URL.revokeObjectURL(mtlLink.href);

    console.log(`OBJ exported: ${filename}.obj, ${filename}.mtl`);
  } catch (error) {
    console.error('OBJ export failed:', error);
    throw error;
  }
}
