import * as THREE from 'three';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import type { CollectedMesh } from './meshCollector';
import { alignToGround } from './meshCollector';

/**
 * THREE.js Object3D를 OBJ Blob으로 변환 (MTL 메테리얼 포함)
 * @param object3D - Export할 3D 객체
 * @param filename - 파일명 (확장자 제외)
 * @param additionalRotation - 추가 회전값 (라디안, X축)
 * @returns OBJ 파일 Blob과 MTL 파일 Blob
 */
export function exportToOBJBlob(object3D: THREE.Object3D, filename: string = 'model', additionalRotation: number = 0): { objBlob: Blob; mtlBlob: Blob } {
  try {
    // 모든 메시 수집 및 변환
    const meshes: Array<{ geometry: THREE.BufferGeometry; material: THREE.Material | THREE.Material[] }> = [];

    object3D.traverse((child) => {
      if (child instanceof THREE.Mesh && child.geometry) {
        const geo = child.geometry.clone();

        // World matrix 적용 (현재 위치/회전/스케일 모두 포함)
        child.updateMatrixWorld(true);
        geo.applyMatrix4(child.matrixWorld);

        // 추가 회전 적용 (QR 판만 눕히기)
        if (additionalRotation !== 0) {
          const rotationMatrix = new THREE.Matrix4().makeRotationX(additionalRotation);
          geo.applyMatrix4(rotationMatrix);
        }

        meshes.push({ geometry: geo, material: child.material });
      }
    });

    if (meshes.length === 0) {
      throw new Error('No meshes found in object');
    }

    // 바운딩 박스 계산하여 바닥면 정렬
    const alignedMeshes = alignToGround(
      meshes.map((m) => ({ ...m, partName: 'default' }))
    );

    // alignToGround는 이미 Y 오프셋을 적용했으므로 offsetY는 0
    const offsetY = 0;

    // 사용된 모든 색상 수집
    const colorMap = new Map<string, THREE.Color>();
    alignedMeshes.forEach(({ material }) => {
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        if (!colorMap.has(hexString)) {
          colorMap.set(hexString, mat.color.clone());
        }
      }
    });

    // OBJ 문자열 생성
    let objString = `# Generated by 3D QR Platform\n`;
    objString += `mtllib ${filename}.mtl\n\n`;

    let vertexOffset = 1;

    alignedMeshes.forEach(({ geometry, material }) => {
      // 메테리얼 색상 감지
      let materialName = 'default';
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        materialName = `color_${hexString}`;
      }

      // 메테리얼 그룹 시작
      objString += `usemtl ${materialName}\n`;

      // Vertex 출력
      const positionAttr = geometry.attributes.position;
      if (!positionAttr) return;

      for (let i = 0; i < positionAttr.count; i++) {
        const x = positionAttr.getX(i);
        const y = positionAttr.getY(i) + offsetY;
        const z = positionAttr.getZ(i);
        objString += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
      }

      // Face 출력
      const index = geometry.index;
      if (index) {
        // Indexed geometry
        for (let i = 0; i < index.count; i += 3) {
          const a = index.getX(i) + vertexOffset;
          const b = index.getX(i + 1) + vertexOffset;
          const c = index.getX(i + 2) + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      } else {
        // Non-indexed geometry
        for (let i = 0; i < positionAttr.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += positionAttr.count;
      objString += '\n';
    });

    // MTL 파일 생성 (동적으로 색상 포함)
    const mtlString = generateMTL(filename, colorMap);

    // Blob 생성
    const objBlob = new Blob([objString], { type: 'text/plain' });
    const mtlBlob = new Blob([mtlString], { type: 'text/plain' });

    return { objBlob, mtlBlob };
  } catch (error) {
    console.error('OBJ export failed:', error);
    throw error;
  }
}

/**
 * MTL 파일 생성 (메테리얼 정보)
 * @param filename - 파일명
 * @param colorMap - 사용된 색상들의 Map
 * @returns MTL 문자열
 */
function generateMTL(filename: string, colorMap: Map<string, THREE.Color>): string {
  let mtlString = `# Material file for ${filename}.obj\n`;
  mtlString += `# Generated by 3D QR Platform\n\n`;

  // 각 색상마다 메테리얼 정의
  colorMap.forEach((color, hexString) => {
    mtlString += `newmtl color_${hexString}\n`;
    mtlString += `Ka ${color.r.toFixed(6)} ${color.g.toFixed(6)} ${color.b.toFixed(6)}\n`;
    mtlString += `Kd ${color.r.toFixed(6)} ${color.g.toFixed(6)} ${color.b.toFixed(6)}\n`;
    mtlString += `Ks 0.500000 0.500000 0.500000\n`;
    mtlString += `Ns 96.078431\n`;
    mtlString += `d 1.000000\n`;
    mtlString += `illum 2\n\n`;
  });

  // 기본 메테리얼 (혹시 모를 경우를 위해)
  if (colorMap.size === 0) {
    mtlString += `newmtl default\n`;
    mtlString += `Ka 0.800000 0.800000 0.800000\n`;
    mtlString += `Kd 0.800000 0.800000 0.800000\n`;
    mtlString += `Ks 0.500000 0.500000 0.500000\n`;
    mtlString += `Ns 96.078431\n`;
    mtlString += `d 1.000000\n`;
    mtlString += `illum 2\n`;
  }

  return mtlString;
}

/**
 * THREE.js Object3D를 OBJ 파일로 변환하여 다운로드
 * @param object3D - Export할 3D 객체
 * @param filename - 저장할 파일명 (확장자 제외)
 */
export function exportToOBJ(object3D: THREE.Object3D, filename: string = 'model') {
  try {
    const { objBlob, mtlBlob } = exportToOBJBlob(object3D, filename);

    // OBJ 파일 다운로드
    const objLink = document.createElement('a');
    objLink.href = URL.createObjectURL(objBlob);
    objLink.download = `${filename}.obj`;
    objLink.click();
    URL.revokeObjectURL(objLink.href);

    // MTL 파일 다운로드
    const mtlLink = document.createElement('a');
    mtlLink.href = URL.createObjectURL(mtlBlob);
    mtlLink.download = `${filename}.mtl`;
    mtlLink.click();
    URL.revokeObjectURL(mtlLink.href);
  } catch (error) {
    console.error('OBJ export failed:', error);
    throw error;
  }
}

/**
 * GLB 파츠들을 OBJ로 변환 (디버깅용, 옆으로 눕혀서 바닥 접지)
 * front.glb와 back.glb만 70도 기울임
 * @param backGltf - back.glb
 * @param brigeGltf - brige.glb
 * @param frontGltf - front.glb
 * @param pinGltf - pin.glb
 * @param filename - 저장할 파일명 (확장자 제외)
 */
export function exportGLBPartsToOBJ(
  backGltf: GLTF,
  brigeGltf: GLTF,
  frontGltf: GLTF,
  pinGltf: GLTF,
  filename: string = 'glb_parts_debug'
) {
  try {
    // 파츠별 회전값 정의 (GLB 파일이 이미 Three.js 좌표계로 변환되어 있음)
    const parts = [
      { name: 'back', gltf: backGltf, rotationX: 0 },
      { name: 'brige', gltf: brigeGltf, rotationX: 0 },
      { name: 'front', gltf: frontGltf, rotationX: 0 },
      { name: 'pin', gltf: pinGltf, rotationX: 0 },
    ];

    // 모든 메시 수집 (파츠별 회전 적용)
    const allMeshes: Array<{ geometry: THREE.BufferGeometry; material: THREE.Material | THREE.Material[] }> = [];

    parts.forEach(({ gltf, rotationX }) => {
      gltf.scene.traverse((child) => {
        if (child instanceof THREE.Mesh && child.geometry) {
          const geo = child.geometry.clone();

          // World matrix 적용
          child.updateMatrixWorld(true);
          geo.applyMatrix4(child.matrixWorld);

          // 파츠별 회전 적용 (front, back만 70도)
          if (rotationX !== 0) {
            const rotationMatrix = new THREE.Matrix4().makeRotationX(rotationX);
            geo.applyMatrix4(rotationMatrix);
          }

          allMeshes.push({ geometry: geo, material: child.material });
        }
      });
    });

    if (allMeshes.length === 0) {
      throw new Error('No meshes found in GLB parts');
    }

    // 바운딩 박스 계산하여 바닥면 정렬
    const alignedMeshes = alignToGround(
      allMeshes.map((m) => ({ ...m, partName: 'default' }))
    );

    // alignToGround는 이미 Y 오프셋을 적용했으므로 offsetY는 0
    const offsetY = 0;

    // 사용된 모든 색상 수집
    const colorMap = new Map<string, THREE.Color>();
    alignedMeshes.forEach(({ material }) => {
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        if (!colorMap.has(hexString)) {
          colorMap.set(hexString, mat.color.clone());
        }
      }
    });

    // OBJ 문자열 생성
    let objString = `# Generated by 3D QR Platform (GLB Parts Debug)\n`;
    objString += `mtllib ${filename}.mtl\n\n`;

    let vertexOffset = 1;

    alignedMeshes.forEach(({ geometry, material }) => {
      // 메테리얼 색상 감지
      let materialName = 'default';
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        materialName = `color_${hexString}`;
      }

      // 메테리얼 그룹 시작
      objString += `usemtl ${materialName}\n`;

      // Vertex 출력
      const positionAttr = geometry.attributes.position;
      if (!positionAttr) return;

      for (let i = 0; i < positionAttr.count; i++) {
        const x = positionAttr.getX(i);
        const y = positionAttr.getY(i) + offsetY;
        const z = positionAttr.getZ(i);
        objString += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
      }

      // Face 출력
      const index = geometry.index;
      if (index) {
        for (let i = 0; i < index.count; i += 3) {
          const a = index.getX(i) + vertexOffset;
          const b = index.getX(i + 1) + vertexOffset;
          const c = index.getX(i + 2) + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      } else {
        for (let i = 0; i < positionAttr.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += positionAttr.count;
      objString += '\n';
    });

    // MTL 파일 생성
    const mtlString = generateMTL(filename, colorMap);

    // Blob 생성 및 다운로드
    const objBlob = new Blob([objString], { type: 'text/plain' });
    const mtlBlob = new Blob([mtlString], { type: 'text/plain' });

    // OBJ 파일 다운로드
    const objLink = document.createElement('a');
    objLink.href = URL.createObjectURL(objBlob);
    objLink.download = `${filename}.obj`;
    objLink.click();
    URL.revokeObjectURL(objLink.href);

    // MTL 파일 다운로드
    const mtlLink = document.createElement('a');
    mtlLink.href = URL.createObjectURL(mtlBlob);
    mtlLink.download = `${filename}.mtl`;
    mtlLink.click();
    URL.revokeObjectURL(mtlLink.href);
  } catch (error) {
    console.error('GLB Parts OBJ export failed:', error);
    throw error;
  }
}

/**
 * CollectedMesh 배열을 OBJ로 export (Preview 씬의 상태 그대로)
 * @param meshes - meshCollector로 수집된 메시들
 * @param filename - 저장할 파일명 (확장자 제외)
 */
export function exportCollectedMeshesToOBJ(
  meshes: CollectedMesh[],
  filename: string = 'obj_export'
) {
  try {
    if (meshes.length === 0) {
      throw new Error('No meshes to export');
    }

    // 사용된 모든 색상 수집
    const colorMap = new Map<string, THREE.Color>();
    meshes.forEach(({ material, partName }) => {
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        if (!colorMap.has(hexString)) {
          colorMap.set(hexString, mat.color.clone());
        }
      } else {
        console.warn(`[OBJ Export] ${partName} has unsupported material type:`, mat?.type || 'undefined');
      }
    });

    // OBJ 문자열 생성
    let objString = `# Generated by 3D QR Platform (Preview Export)\n`;
    objString += `mtllib ${filename}.mtl\n\n`;

    let vertexOffset = 1;

    meshes.forEach(({ geometry, material, partName }) => {
      // 메테리얼 색상 감지
      let materialName = 'default';
      let mat = Array.isArray(material) ? material[0] : material;
      if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
        const hexString = mat.color.getHexString();
        materialName = `color_${hexString}`;
      }

      // 그룹 코멘트 (파츠 이름)
      objString += `# Part: ${partName}\n`;

      // 메테리얼 그룹 시작
      objString += `usemtl ${materialName}\n`;

      // Vertex 출력
      const positionAttr = geometry.attributes.position;
      if (!positionAttr) return;

      for (let i = 0; i < positionAttr.count; i++) {
        const x = positionAttr.getX(i);
        const y = positionAttr.getY(i);
        const z = positionAttr.getZ(i);
        objString += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
      }

      // Face 출력
      const index = geometry.index;
      if (index) {
        for (let i = 0; i < index.count; i += 3) {
          const a = index.getX(i) + vertexOffset;
          const b = index.getX(i + 1) + vertexOffset;
          const c = index.getX(i + 2) + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      } else {
        for (let i = 0; i < positionAttr.count; i += 3) {
          const a = i + vertexOffset;
          const b = i + 1 + vertexOffset;
          const c = i + 2 + vertexOffset;
          objString += `f ${a} ${b} ${c}\n`;
        }
      }

      vertexOffset += positionAttr.count;
      objString += '\n';
    });

    // MTL 파일 생성
    const mtlString = generateMTL(filename, colorMap);

    // Blob 생성 및 다운로드
    const objBlob = new Blob([objString], { type: 'text/plain' });
    const mtlBlob = new Blob([mtlString], { type: 'text/plain' });

    // OBJ 파일 다운로드
    const objLink = document.createElement('a');
    objLink.href = URL.createObjectURL(objBlob);
    objLink.download = `${filename}.obj`;
    objLink.click();
    URL.revokeObjectURL(objLink.href);

    // MTL 파일 다운로드
    const mtlLink = document.createElement('a');
    mtlLink.href = URL.createObjectURL(mtlBlob);
    mtlLink.download = `${filename}.mtl`;
    mtlLink.click();
    URL.revokeObjectURL(mtlLink.href);
  } catch (error) {
    console.error('Preview meshes OBJ export failed:', error);
    throw error;
  }
}
