/**
 * 장바구니 아이템으로부터 OBJ/MTL Blob 생성
 */

import type { CartItem } from '../store/useCartStore';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import {
  collectGLBMeshes,
  collectQRGeometries,
  applyGlobalRotation,
  alignToGround,
  type CollectedMesh,
} from './meshCollector';
import type { Transform } from '../store/objPreviewStore';
import * as THREE from 'three';

interface OBJBlobs {
  plateObjBlob: Blob;
  plateMtlBlob: Blob;
  standObjBlob: Blob;
  standMtlBlob: Blob;
}

interface GLTFs {
  back: GLTF;
  brige: GLTF;
  front: GLTF;
  pin: GLTF;
}

interface Transforms {
  backTransform: Transform;
  brigeTransform: Transform;
  frontTransform: Transform;
  pinTransform: Transform;
  globalRotation: { x: number; y: number; z: number };
}

/**
 * CollectedMesh 배열로부터 OBJ/MTL 문자열 생성
 */
function generateOBJMTLStrings(
  meshes: CollectedMesh[],
  filename: string
): { objString: string; mtlString: string } {
  // 사용된 모든 색상 수집
  const colorMap = new Map<string, THREE.Color>();
  meshes.forEach(({ material }) => {
    let mat = Array.isArray(material) ? material[0] : material;
    if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
      const hexString = mat.color.getHexString();
      if (!colorMap.has(hexString)) {
        colorMap.set(hexString, mat.color.clone());
      }
    }
  });

  // OBJ 문자열 생성
  let objString = `# Generated by 3D QR Platform\n`;
  objString += `mtllib ${filename}.mtl\n\n`;

  let vertexOffset = 1;

  meshes.forEach(({ geometry, material, partName }) => {
    // 메테리얼 색상 감지
    let materialName = 'default';
    let mat = Array.isArray(material) ? material[0] : material;
    if (mat instanceof THREE.MeshStandardMaterial || mat instanceof THREE.MeshBasicMaterial) {
      const hexString = mat.color.getHexString();
      materialName = `color_${hexString}`;
    }

    // 그룹 코멘트 (파츠 이름)
    objString += `# Part: ${partName}\n`;

    // 메테리얼 그룹 시작
    objString += `usemtl ${materialName}\n`;

    // Vertex 출력
    const positionAttr = geometry.attributes.position;
    if (!positionAttr) return;

    for (let i = 0; i < positionAttr.count; i++) {
      const x = positionAttr.getX(i);
      const y = positionAttr.getY(i);
      const z = positionAttr.getZ(i);
      objString += `v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}\n`;
    }

    // Face 출력
    const index = geometry.index;
    if (index) {
      for (let i = 0; i < index.count; i += 3) {
        const a = index.getX(i) + vertexOffset;
        const b = index.getX(i + 1) + vertexOffset;
        const c = index.getX(i + 2) + vertexOffset;
        objString += `f ${a} ${b} ${c}\n`;
      }
    } else {
      for (let i = 0; i < positionAttr.count; i += 3) {
        const a = i + vertexOffset;
        const b = i + 1 + vertexOffset;
        const c = i + 2 + vertexOffset;
        objString += `f ${a} ${b} ${c}\n`;
      }
    }

    vertexOffset += positionAttr.count;
    objString += '\n';
  });

  // MTL 문자열 생성
  let mtlString = `# Material file for ${filename}.obj\n`;
  mtlString += `# Generated by 3D QR Platform\n\n`;

  colorMap.forEach((color, hexString) => {
    mtlString += `newmtl color_${hexString}\n`;
    mtlString += `Ka ${color.r.toFixed(6)} ${color.g.toFixed(6)} ${color.b.toFixed(6)}\n`;
    mtlString += `Kd ${color.r.toFixed(6)} ${color.g.toFixed(6)} ${color.b.toFixed(6)}\n`;
    mtlString += `Ks 0.500000 0.500000 0.500000\n`;
    mtlString += `Ns 96.078431\n`;
    mtlString += `d 1.000000\n`;
    mtlString += `illum 2\n\n`;
  });

  // 기본 메테리얼
  if (colorMap.size === 0) {
    mtlString += `newmtl default\n`;
    mtlString += `Ka 0.800000 0.800000 0.800000\n`;
    mtlString += `Kd 0.800000 0.800000 0.800000\n`;
    mtlString += `Ks 0.500000 0.500000 0.500000\n`;
    mtlString += `Ns 96.078431\n`;
    mtlString += `d 1.000000\n`;
    mtlString += `illum 2\n`;
  }

  return { objString, mtlString };
}

/**
 * 장바구니 아이템으로부터 OBJ/MTL Blob 생성
 *
 * @param item - 장바구니 아이템
 * @param gltfs - GLB 파츠 데이터
 * @param transforms - OBJ 변환 설정
 * @returns OBJ/MTL Blob들
 */
export async function generateOBJFromCartItem(
  item: CartItem,
  gltfs: GLTFs,
  transforms: Transforms
): Promise<OBJBlobs> {
  try {
    // 1. GLB 메시 수집
    let allMeshes: CollectedMesh[] = [];

    allMeshes.push(...collectGLBMeshes(gltfs.back, 'back', transforms.backTransform, item.plateConfig.plateColor));
    allMeshes.push(...collectGLBMeshes(gltfs.brige, 'brige', transforms.brigeTransform, item.plateConfig.plateColor));
    allMeshes.push(...collectGLBMeshes(gltfs.front, 'front', transforms.frontTransform, item.plateConfig.plateColor));
    allMeshes.push(...collectGLBMeshes(gltfs.pin, 'pin', transforms.pinTransform, item.plateConfig.plateColor));

    // 2. QR/텍스트/이미지 추가
    if (item.geometries) {
      allMeshes.push(
        ...collectQRGeometries(
          item.geometries.qr,
          item.geometries.text,
          item.geometries.image,
          item.geometries.qrPosition,
          item.geometries.qrQuaternion,
          item.geometries.textPosition,
          item.geometries.textQuaternion,
          item.geometries.imagePosition,
          item.geometries.imageQuaternion,
          item.geometries.qrColor,
          item.geometries.zScale,
          transforms.frontTransform
        )
      );
    }

    // 3. 변환 적용
    allMeshes = applyGlobalRotation(allMeshes, transforms.globalRotation);
    allMeshes = alignToGround(allMeshes);

    // 4. OBJ/MTL 문자열 생성
    const { objString, mtlString } = generateOBJMTLStrings(allMeshes, 'model');

    // 5. Blob 생성 및 반환
    const plateObjBlob = new Blob([objString], { type: 'text/plain' });
    const plateMtlBlob = new Blob([mtlString], { type: 'text/plain' });

    // 백엔드 API는 stand_obj/mtl도 요구하지만, GLB 기반이므로 동일한 파일 전송
    const standObjBlob = plateObjBlob;
    const standMtlBlob = plateMtlBlob;

    return {
      plateObjBlob,
      plateMtlBlob,
      standObjBlob,
      standMtlBlob,
    };
  } catch (error) {
    console.error('Failed to generate OBJ from cart item:', error);
    throw new Error('OBJ 파일 생성에 실패했습니다.');
  }
}
